{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "<!-- Before reporting: search existing issues and check the FAQ. -->\r\n\r\n- `nvim --version`: 0.4.4\r\n- `vim -u DEFAULTS` (version: ) behaves differently?\r\n- Operating system/version: Mac 10.15.7\r\n- Terminal name/version: iTerm2\r\n- `$TERM`: screen-256color\r\n\r\n### Steps to reproduce using `nvim -u NORC`\r\n\r\n```\r\nnvim -u NORC\r\n# Alternative for shell-related problems:\r\n# env -i TERM=ansi-256color \"$(which nvim)\"\r\n\r\n:chechhealth\r\n```\r\n\r\nI saw issue #12407 and someone mention system issues. In ` /Users/jcostanzo/.local/share/nvim/` directory there is not a shada dir. \r\n\r\n### Actual behaviour\r\n\r\n![image](https://user-images.githubusercontent.com/655716/98004794-5612da80-1dbe-11eb-837c-c195a0ced118.png)\r\n\r\n\r\n### Expected behaviour\r\n\r\nNot see error",
    "closed_at": "2020-12-14T02:49:30Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/8740057?v=4",
        "events_url": "https://api.github.com/users/janlazo/events{/privacy}",
        "followers_url": "https://api.github.com/users/janlazo/followers",
        "following_url": "https://api.github.com/users/janlazo/following{/other_user}",
        "gists_url": "https://api.github.com/users/janlazo/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/janlazo",
        "id": 8740057,
        "login": "janlazo",
        "node_id": "MDQ6VXNlcjg3NDAwNTc=",
        "organizations_url": "https://api.github.com/users/janlazo/orgs",
        "received_events_url": "https://api.github.com/users/janlazo/received_events",
        "repos_url": "https://api.github.com/users/janlazo/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/janlazo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/janlazo/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/janlazo",
        "user_view_type": "public"
    },
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "# Please correctly fill out the form given above\r\n\r\n- Did you try `vim -u DEFAULTS`?\r\n- `vim -u DEFAULTS` (version: **???** ) behaves differently?\r\n- ### Steps to reproduce using `nvim -u NORC`?",
            "created_at": "2020-11-06T14:20:14Z",
            "html_url": "https://github.com/neovim/neovim/issues/13218#issuecomment-723105147",
            "id": 723105147,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/13218",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcyMzEwNTE0Nw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/723105147/reactions"
            },
            "updated_at": "2020-11-06T14:20:14Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/723105147",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/56714626?v=4",
                "events_url": "https://api.github.com/users/subnut/events{/privacy}",
                "followers_url": "https://api.github.com/users/subnut/followers",
                "following_url": "https://api.github.com/users/subnut/following{/other_user}",
                "gists_url": "https://api.github.com/users/subnut/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/subnut",
                "id": 56714626,
                "login": "subnut",
                "node_id": "MDQ6VXNlcjU2NzE0NjI2",
                "organizations_url": "https://api.github.com/users/subnut/orgs",
                "received_events_url": "https://api.github.com/users/subnut/received_events",
                "repos_url": "https://api.github.com/users/subnut/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/subnut/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/subnut/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/subnut",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "So it seems with `nvim -u DEFAULTS` I do not get the error. Guess I need to hunt, what in my file could be causing this",
            "created_at": "2020-11-10T13:21:28Z",
            "html_url": "https://github.com/neovim/neovim/issues/13218#issuecomment-724697727",
            "id": 724697727,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/13218",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcyNDY5NzcyNw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/724697727/reactions"
            },
            "updated_at": "2020-11-10T13:21:28Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/724697727",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/655716?v=4",
                "events_url": "https://api.github.com/users/jrock2004/events{/privacy}",
                "followers_url": "https://api.github.com/users/jrock2004/followers",
                "following_url": "https://api.github.com/users/jrock2004/following{/other_user}",
                "gists_url": "https://api.github.com/users/jrock2004/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jrock2004",
                "id": 655716,
                "login": "jrock2004",
                "node_id": "MDQ6VXNlcjY1NTcxNg==",
                "organizations_url": "https://api.github.com/users/jrock2004/orgs",
                "received_events_url": "https://api.github.com/users/jrock2004/received_events",
                "repos_url": "https://api.github.com/users/jrock2004/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jrock2004/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jrock2004/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jrock2004",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "@jrock2004 See, this is exactly why that initial form is given. It helps us avoid unnecessary issues.\r\nI advise you to close this issue. In case you find something that needs our attention, you can reopen it.\r\n<br>\r\nRegards\r\nsubnut",
            "created_at": "2020-11-10T13:37:54Z",
            "html_url": "https://github.com/neovim/neovim/issues/13218#issuecomment-724706658",
            "id": 724706658,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/13218",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcyNDcwNjY1OA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/724706658/reactions"
            },
            "updated_at": "2020-11-10T13:37:54Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/724706658",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/56714626?v=4",
                "events_url": "https://api.github.com/users/subnut/events{/privacy}",
                "followers_url": "https://api.github.com/users/subnut/followers",
                "following_url": "https://api.github.com/users/subnut/following{/other_user}",
                "gists_url": "https://api.github.com/users/subnut/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/subnut",
                "id": 56714626,
                "login": "subnut",
                "node_id": "MDQ6VXNlcjU2NzE0NjI2",
                "organizations_url": "https://api.github.com/users/subnut/orgs",
                "received_events_url": "https://api.github.com/users/subnut/received_events",
                "repos_url": "https://api.github.com/users/subnut/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/subnut/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/subnut/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/subnut",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "@jrock2004 Do you have either of the following settings in place?\r\n\r\n- `shadafile` is set to `NONE` or `-i NONE` is set as a command line option at startup.\r\n- Set shada file with the `shada (viminfo)` option `n`.\r\n\r\nIn that case, `:checkhelath` could show a false error. Fixed at #13291. Does #13291 solve your problem?",
            "created_at": "2020-11-14T03:32:36Z",
            "html_url": "https://github.com/neovim/neovim/issues/13218#issuecomment-727136953",
            "id": 727136953,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/13218",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcyNzEzNjk1Mw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/727136953/reactions"
            },
            "updated_at": "2020-11-14T03:32:36Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/727136953",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/11682285?v=4",
                "events_url": "https://api.github.com/users/erw7/events{/privacy}",
                "followers_url": "https://api.github.com/users/erw7/followers",
                "following_url": "https://api.github.com/users/erw7/following{/other_user}",
                "gists_url": "https://api.github.com/users/erw7/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/erw7",
                "id": 11682285,
                "login": "erw7",
                "node_id": "MDQ6VXNlcjExNjgyMjg1",
                "organizations_url": "https://api.github.com/users/erw7/orgs",
                "received_events_url": "https://api.github.com/users/erw7/received_events",
                "repos_url": "https://api.github.com/users/erw7/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/erw7/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/erw7/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/erw7",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "I'm getting the same error with the latest neovim. It seems that it's looking in the wrong directory. In windows I'm seeing the shada dir in nvim\\Kickstart\\Kickstart-data. Similarly for Lazy and AstroVim: .state\\nvim\\AstroNvim/shada/main.shada but it's in .state\\nvim\\AstroNvim\\AstroNvim-data/shada/main.shada.\n\nI thought about linking to it but not sure if it is just an false error due to paths in the health check or if it is a real error since the data actually exists. Not 100% sure if it's being used since I'm new to neovim and still setting things up. I also created a custom lua router which modifies the paths to try to put everything in subdirectories under nvim so it could something related to that. The issue here suggests it may be due to the path being hard coded in the health check and unrelated to my router code.",
            "created_at": "2025-10-06T06:20:22Z",
            "html_url": "https://github.com/neovim/neovim/issues/13218#issuecomment-3370070696",
            "id": 3370070696,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/13218",
            "node_id": "IC_kwDOAPphoM7I3zKo",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/3370070696/reactions"
            },
            "updated_at": "2025-10-06T06:20:22Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/3370070696",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/202556375?v=4",
                "events_url": "https://api.github.com/users/Universal-Invariant/events{/privacy}",
                "followers_url": "https://api.github.com/users/Universal-Invariant/followers",
                "following_url": "https://api.github.com/users/Universal-Invariant/following{/other_user}",
                "gists_url": "https://api.github.com/users/Universal-Invariant/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Universal-Invariant",
                "id": 202556375,
                "login": "Universal-Invariant",
                "node_id": "U_kgDODBLD1w",
                "organizations_url": "https://api.github.com/users/Universal-Invariant/orgs",
                "received_events_url": "https://api.github.com/users/Universal-Invariant/received_events",
                "repos_url": "https://api.github.com/users/Universal-Invariant/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Universal-Invariant/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Universal-Invariant/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Universal-Invariant",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 5,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/13218/comments",
    "created_at": "2020-11-03T15:22:58Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/13218/events",
    "html_url": "https://github.com/neovim/neovim/issues/13218",
    "id": 735412124,
    "issue_dependencies_summary": {
        "blocked_by": 0,
        "blocking": 0,
        "total_blocked_by": 0,
        "total_blocking": 0
    },
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/13218/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU3MzU0MTIxMjQ=",
    "number": 13218,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/13218/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/13218/timeline",
    "title": "ERROR: shada file is not readable",
    "type": null,
    "updated_at": "2025-10-06T06:20:22Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/13218",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/655716?v=4",
        "events_url": "https://api.github.com/users/jrock2004/events{/privacy}",
        "followers_url": "https://api.github.com/users/jrock2004/followers",
        "following_url": "https://api.github.com/users/jrock2004/following{/other_user}",
        "gists_url": "https://api.github.com/users/jrock2004/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/jrock2004",
        "id": 655716,
        "login": "jrock2004",
        "node_id": "MDQ6VXNlcjY1NTcxNg==",
        "organizations_url": "https://api.github.com/users/jrock2004/orgs",
        "received_events_url": "https://api.github.com/users/jrock2004/received_events",
        "repos_url": "https://api.github.com/users/jrock2004/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/jrock2004/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jrock2004/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/jrock2004",
        "user_view_type": "public"
    }
}