{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "### Neovim version (nvim -v)\n\nNVIM v0.8.0 release\n\n### Vim (not Nvim) behaves the same?\n\nnot sure, might be N/A\n\n### Operating system/version\n\nArch Linux\n\n### Terminal name/version\n\nxterm (374)\n\n### $TERM environment variable\n\nxterm-256color\n\n### Installation\n\nsystem package manager\n\n### How to reproduce the issue\n\n1. Using the following vimrc:\r\n```\r\nlua <<EOF\r\nlocal buffer = vim.api.nvim_create_buf(false, false)\r\nvim.api.nvim_buf_set_option(buffer, \"buftype\", \"nofile\")\r\n\r\nlocal lines = {'a', 'b'}   -- seems to only happen when #lines >= 2\r\nlocal timer = vim.loop.new_timer()\r\ntimer:start(0, 100, vim.schedule_wrap(function()\r\n    vim.pretty_print(vim.fn.getbufinfo())\r\n    vim.api.nvim_buf_set_lines(buffer, 0, -1, false, lines)\r\nend))\r\nEOF\r\n```\r\n2. Run `nvim --clean -u /path/to/vimrc`\r\n3. Quit nvim (I seem to get error more often when using `ZZ` or `ZQ`).\r\n\r\nIn actual usage, I'm getting this from the interaction of two plugins (https://github.com/nvim-zh/colorful-winsep.nvim and https://github.com/rhysd/committia.vim), and I'm including those steps in here for reference:\r\n1. Download/git clone the following plugins: \r\n    * https://github.com/nvim-zh/colorful-winsep.nvim\r\n    * https://github.com/rhysd/committia.vim\r\n1. Make the following vimrc:\r\n```\r\nset runtimepath+=/path/to/colorful-winsep.nvim\r\nset runtimepath+=/path/to/committia.vim\r\nlet g:committia_min_window_width = &columns / 2\r\nlua require('colorful-winsep').setup{}\r\n```\r\n1. Inside any git repo, run `GIT_EDITOR='nvim --clean -u /path/to/above/vimrc' git commit`\r\n1. Quit nvim by typing `ZQ`\n\n### Expected behavior\n\nNo error is printed.\n\n### Actual behavior\n\nAbout 50% of the time, the following error is printed back to the terminal after the nvim tui has exited\r\n```\r\n{ {    bufnr = 1,    changed = 0,    changedtick = -1,    hidden = 0,    lastused = 1669270126,    linecount = 1,    listed = 1,    lnum = 1,    loaded = 0,    name = \"\",    variables = {      changedtick = -1    },    windows = { 1000 }  }, {    bufnr = 2,    changed = 0,    changedtick = 5,    hidden = 0,    lastused = 0,    linecount = 2,    listed = 0,    lnum = 0,    loaded = 0,    name = \"\",    variables = {      changedtick = 5    },    windows = {}  } }\r\nError executing vim.schedule lua callback: [string \":lua\"]:8: Vim:E322: line number out of range: 1 past the end\r\nstack traceback:\r\n\t[C]: in function 'nvim_buf_set_lines'\r\n\t[string \":lua\"]:8: in function ''\r\n\tvim/_editor.lua: in function <vim/_editor.lua:0>\r\n```\r\n\r\nI don't think this causing any adverse functional impact, i.e. nvim still works, it just prints this error as well.",
    "closed_at": null,
    "closed_by": null,
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Related: https://github.com/neovim/neovim/commit/75a5674cd2d0921400d2d2c7a9ce9701c58c5b25",
            "created_at": "2022-11-24T08:54:23Z",
            "html_url": "https://github.com/neovim/neovim/issues/21171#issuecomment-1326136429",
            "id": 1326136429,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/21171",
            "node_id": "IC_kwDOAPphoM5PCzxt",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1326136429/reactions"
            },
            "updated_at": "2022-11-24T08:54:23Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1326136429",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/21171/comments",
    "created_at": "2022-11-24T06:17:07Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/21171/events",
    "html_url": "https://github.com/neovim/neovim/issues/21171",
    "id": 1462819163,
    "labels": [
        {
            "color": "c5def5",
            "default": false,
            "description": null,
            "id": 520282574,
            "name": "event-loop",
            "node_id": "MDU6TGFiZWw1MjAyODI1NzQ=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/event-loop"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/21171/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM5XMNlb",
    "number": 21171,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/21171/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "open",
    "state_reason": null,
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/21171/timeline",
    "title": "(Vim:E322: line number out of range: 1 past the end) with nvim_buf_set_lines",
    "type": {
        "color": "red",
        "created_at": "2024-01-25T10:10:19Z",
        "description": "An unexpected problem or behavior",
        "id": 597163,
        "is_enabled": true,
        "name": "Bug",
        "node_id": "IT_kwDOAGK_Pc4ACRyr",
        "updated_at": "2024-07-26T10:12:30Z"
    },
    "updated_at": "2025-07-02T08:36:02Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/21171",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1336117?v=4",
        "events_url": "https://api.github.com/users/lincheney/events{/privacy}",
        "followers_url": "https://api.github.com/users/lincheney/followers",
        "following_url": "https://api.github.com/users/lincheney/following{/other_user}",
        "gists_url": "https://api.github.com/users/lincheney/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/lincheney",
        "id": 1336117,
        "login": "lincheney",
        "node_id": "MDQ6VXNlcjEzMzYxMTc=",
        "organizations_url": "https://api.github.com/users/lincheney/orgs",
        "received_events_url": "https://api.github.com/users/lincheney/received_events",
        "repos_url": "https://api.github.com/users/lincheney/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/lincheney/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lincheney/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/lincheney",
        "user_view_type": "public"
    }
}