{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Problem\n\nI'm getting an error message when I start Neovim, as well as with --clean. On start up I get this error:\n```\nError detected while processing TermResponse Autocommands for \"*\":\nError executing lua callback: /usr/share/nvim/runtime/lua/vim/termcap.lua:38: attempt to call method 'match' (a nil value)\nstack traceback:\n  /usr/share/nvim/runtime/lua/vim/termcap.lua:38: in function </usr/share/nvim/runtime/lua/vim/termcap.lua:36>\nError detected while processing TermResponse Autocommands for \"*\":\nError executing lua callback: /usr/share/nvim/runtime/lua/vim/termcap.lua:38: attempt to call method 'match' (a nil value)\nstack traceback:\n  /usr/share/nvim/runtime/lua/vim/termcap.lua:38: in function </usr/share/nvim/runtime/lua/vim/termcap.lua:36>\n```\nI'm running the recent 0.11 release (via the extracted AppImage), on WSL2 Ubuntu, inside tmux and the error appears twice (asking to press enter each time).\n\nI tried to reproduce without tmux as well, and then the error appears 4 times.\n\nIt doesn't appear to affect much functionality, as I'm able to use my config just fine after the message.\n\n### Steps to reproduce\n\nnvim --clean\n\n### Expected behavior\n\nOpen nvim without any error messages\n\n### Nvim version (nvim -v)\n\nNVIM v0.11.0 Build type: Release LuaJIT 2.1.1741730670\n\n### Vim (not Nvim) behaves the same?\n\nno, vim 9.1.697\n\n### Operating system/version\n\nWindows 11, WSL2 Ubuntu 24.04.2 LTS\n\n### Terminal name/version\n\nWindows Terminal\n\n### $TERM environment variable\n\nscreen-256color\n\n### Installation\n\nAppImage",
    "closed_at": null,
    "closed_by": null,
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Can you try applying this change to the file:\n```diff\ndiff --git a/runtime/lua/vim/termcap.lua b/runtime/lua/vim/termcap.lua\nindex 2789aacb90..2a2ed9af6c 100644\n--- a/runtime/lua/vim/termcap.lua\n+++ b/runtime/lua/vim/termcap.lua\n@@ -33,8 +33,8 @@ function M.query(caps, cb)\n \n   local id = vim.api.nvim_create_autocmd('TermResponse', {\n     nested = true,\n-    callback = function(args)\n-      local resp = args.data.sequence ---@type string\n+    callback = function()\n+      local resp = vim.v.termresponse ---@type string\n       local k, rest = resp:match('^\\027P1%+r(%x+)(.*)$')\n       if k and rest then\n         local cap = vim.text.hexdecode(k)\n```\nand then running `nvim --clean --luamod-dev` to see if the error still happens?",
            "created_at": "2025-03-27T09:43:42Z",
            "html_url": "https://github.com/neovim/neovim/issues/33081#issuecomment-2757358957",
            "id": 2757358957,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/33081",
            "node_id": "IC_kwDOAPphoM6kWfVt",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2757358957/reactions"
            },
            "updated_at": "2025-03-27T09:44:38Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2757358957",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hi, yes I now get the slightly different error:\n\n```\nError detected while processing TermResponse Autocommands for \"*\":\nError executing lua callback: /usr/share/nvim/runtime/lua/vim/_defaults.lua:\n689: attempt to call method 'match' (a nil value)\nstack traceback:\n        /usr/share/nvim/runtime/lua/vim/_defaults.lua:689: in function 'parseosc11'\n        /usr/share/nvim/runtime/lua/vim/_defaults.lua:716: in function </usr/share/nvim/runtime/lua/vim/_defaults.lua:714>\n```\n\nAlthough, without the --luamod-dev flag, the error seems to have disappeared.",
            "created_at": "2025-03-27T15:01:34Z",
            "html_url": "https://github.com/neovim/neovim/issues/33081#issuecomment-2758390009",
            "id": 2758390009,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/33081",
            "node_id": "IC_kwDOAPphoM6kabD5",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2758390009/reactions"
            },
            "updated_at": "2025-03-27T15:01:34Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2758390009",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/6692387?v=4",
                "events_url": "https://api.github.com/users/olijg/events{/privacy}",
                "followers_url": "https://api.github.com/users/olijg/followers",
                "following_url": "https://api.github.com/users/olijg/following{/other_user}",
                "gists_url": "https://api.github.com/users/olijg/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/olijg",
                "id": 6692387,
                "login": "olijg",
                "node_id": "MDQ6VXNlcjY2OTIzODc=",
                "organizations_url": "https://api.github.com/users/olijg/orgs",
                "received_events_url": "https://api.github.com/users/olijg/received_events",
                "repos_url": "https://api.github.com/users/olijg/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/olijg/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/olijg/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/olijg",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Hmm that's strange, as without `--luamod-dev` the change should have no effect. The error may be timing-dependent. Does it consistently happen when you run `nvim` with the same arguments multiple times?",
            "created_at": "2025-03-28T00:46:46Z",
            "html_url": "https://github.com/neovim/neovim/issues/33081#issuecomment-2759900007",
            "id": 2759900007,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/33081",
            "node_id": "IC_kwDOAPphoM6kgLtn",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2759900007/reactions"
            },
            "updated_at": "2025-03-28T00:46:46Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2759900007",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 3,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/33081/comments",
    "created_at": "2025-03-27T09:36:37Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/33081/events",
    "html_url": "https://github.com/neovim/neovim/issues/33081",
    "id": 2952247966,
    "labels": [
        {
            "color": "C5DEF5",
            "default": false,
            "description": "events, autocommands",
            "id": 3341085842,
            "name": "events",
            "node_id": "MDU6TGFiZWwzMzQxMDg1ODQy",
            "url": "https://api.github.com/repos/neovim/neovim/labels/events"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/33081/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM6v97qe",
    "number": 33081,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/33081/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "open",
    "state_reason": null,
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/33081/timeline",
    "title": "Error while processing TermResponse Autocommands",
    "type": {
        "color": "red",
        "created_at": "2024-01-25T10:10:19Z",
        "description": "An unexpected problem or behavior",
        "id": 597163,
        "is_enabled": true,
        "name": "Bug",
        "node_id": "IT_kwDOAGK_Pc4ACRyr",
        "updated_at": "2024-07-26T10:12:30Z"
    },
    "updated_at": "2025-03-28T00:46:47Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/33081",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/6692387?v=4",
        "events_url": "https://api.github.com/users/olijg/events{/privacy}",
        "followers_url": "https://api.github.com/users/olijg/followers",
        "following_url": "https://api.github.com/users/olijg/following{/other_user}",
        "gists_url": "https://api.github.com/users/olijg/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/olijg",
        "id": 6692387,
        "login": "olijg",
        "node_id": "MDQ6VXNlcjY2OTIzODc=",
        "organizations_url": "https://api.github.com/users/olijg/orgs",
        "received_events_url": "https://api.github.com/users/olijg/received_events",
        "repos_url": "https://api.github.com/users/olijg/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/olijg/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/olijg/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/olijg",
        "user_view_type": "public"
    }
}