{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "// cc @rafaeln\r\n\r\n[Related issue](https://github.com/roxma/nvim-completion-manager/issues/35#issuecomment-284049103)\r\n\r\nRecently I [changed the event loop style into nvim.next_message](https://github.com/roxma/nvim-completion-manager/commit/d259f53873081fb9c3dd14f53cae5aa87272c00e) in order to simplify the async architecture and avoid concurrent issue. But somehow the `nvim.next_message` returns `None` unexpectedly which cause the loop to exit.\r\n\r\nThis issue is reproduced by @rafaeln and here's the log files with DEBUG LEVEL:\r\n\r\nhttps://www.dropbox.com/sh/cq41u8afyop4yth/AABwC1bmBLNWzgRk2JgA2WLXa?dl=0\r\n\r\nHere's the interesting part I've extracted:\r\n\r\n```\r\n2017-03-03 11:15:14,512 [DEBUG @ base.py:run:138] 6073 - Entering event loop\r\n2017-03-03 11:15:14,512 [DEBUG @ base.py:run:140] 6073 - Exited event loop\r\n2017-03-03 11:15:14,512 [ERROR @ cm_start.py:run_event_loop:167] 6073 - Error processing notification <['notification', 'cm_complete_timeout', [{'cm-keyword-continue': {'channel': {'id': 6, 'module': 'cm_sources.cm_keyword_continue', 'type': 'python3', 'events': []}, 'word_pattern': '\\\\S+', 'abbreviation': '', 'cm_refresh_patterns': ['\\\\s+$', '^$'], 'priority': 4, 'enable': True, 'early_cache': 1, 'sort': 0, 'name': 'cm-keyword-continue', 'cm_refresh_min_word_len': 4}, 'cm-gocode': {'name': 'cm-gocode', 'scopes': ['go'], 'channel': {'module': 'cm_sources.cm_gocode', 'type': 'python3', 'events': []}, 'abbreviation': 'Go', 'cm_refresh_patterns': ['\\\\.(\\\\w*)$'], 'priority': 9, 'enable': True, 'early_cache': 1, 'sort': 1, 'scoping': True, 'cm_refresh_min_word_len': 3}, 'cm-bufkeyword': {'channel': {'id': 3, 'module': 'cm_sources.cm_bufkeyword', 'type': 'python3', 'events': ['CursorHold', 'CursorHoldI', 'BufEnter', 'BufWritePost', 'TextChangedI']}, 'abbreviation': 'Key', 'priority': 5, 'enable': True, 'early_cache': 1, 'sort': 1, 'name': 'cm-bufkeyword', 'cm_refresh_min_word_len': 4}, 'cm-ultisnips': {'cm_refresh': 'cm#sources#ultisnips#cm_refresh', 'abbreviation': 'Snip', 'priority': 7, 'word_pattern': '\\\\S+', 'enable': 1, 'early_cache': 0, 'sort': 1, 'name': 'cm-ultisnips', 'cm_refresh_min_word_len': 3}, 'cm-tags': {'channel': {'id': 4, 'module': 'cm_sources.cm_tags', 'type': 'python3', 'events': ['WinEnter']}, 'abbreviation': 'Tag', 'priority': 6, 'enable': True, 'early_cache': 1, 'sort': 1, 'name': 'cm-tags', 'cm_refresh_min_word_len': 4}, 'cm-filepath': {'channel': {'id': 5, 'module': 'cm_sources.cm_filepath', 'type': 'python3', 'events': []}, 'abbreviation': 'path', 'cm_refresh_patterns': ['[0-9a-zA-Z_\\\\-\\\\.\\\\\\\\\\\\/~\\\\$]{4,}$', '(\\\\.[\\\\/\\\\\\\\]|[a-zA-Z]:\\\\\\\\|~\\\\/)[0-9a-zA-Z_\\\\-\\\\.\\\\\\\\\\\\/~\\\\$]*$'], 'priority': 6, 'enable': True, 'early_cache': 1, 'sort': 1, 'name': 'cm-filepath', 'cm_refresh_min_word_len': 4}, 'cm-tmux': {'channel': {'id': 7, 'module': 'cm_sources.cm_tmux', 'type': 'python3', 'events': ['CursorHold', 'CursorHoldI', 'FocusGained', 'BufEnter']}, 'abbreviation': 'Tmux', 'priority': 4, 'enable': True, 'early_cache': 1, 'sort': 1, 'name': 'cm-tmux', 'cm_refresh_min_word_len': 4}, 'cm-jedi': {'name': 'cm-jedi', 'scopes': ['python'], 'channel': {'module': 'cm_sources.cm_jedi', 'type': 'python3', 'events': []}, 'abbreviation': 'Py', 'cm_refresh_patterns': ['^(import|from).*?\\\\s(\\\\w*)$', '\\\\.\\\\w*$', '\\\\(\\\\s?(\\\\w*)$', ',\\\\s?(\\\\w*)$'], 'priority': 9, 'enable': True, 'early_cache': 1, 'sort': 1, 'scoping': True, 'cm_refresh_min_word_len': 3}, 'cm-css': {'name': 'cm-css', 'scopes': ['css', 'scss'], 'cm_refresh': {'omnifunc': 'csscomplete#CompleteCSS'}, 'abbreviation': 'css', 'cm_refresh_patterns': [':\\\\s+\\\\w*$'], 'priority': 9, 'enable': 1, 'early_cache': 0, 'sort': 1, 'scoping': 1, 'cm_refresh_min_word_len': 3}}, {'force': 0, 'lnum': 3, 'filetype': 'text', 'bufnr': 1, 'scope': 'text', 'filepath': '/home/rafael/test.txt', 'typed': 'some', 'col': 5, 'changedtick': 7, 'curpos': [0, 3, 5, 0, 5]}]]>, msg:\r\nTraceback (most recent call last):\r\n  File \"/home/rafael/.config/nvim/bundle/nvim-completion-manager/pythonx/cm_start.py\", line 165, in run_event_loop\r\n    on_notification(method,msg[2])\r\n  File \"/home/rafael/.config/nvim/bundle/nvim-completion-manager/pythonx/cm_start.py\", line 145, in on_notification\r\n    func(*args)\r\n  File \"/home/rafael/Dropbox/dotfiles/.vim/bundle/nvim-completion-manager/pythonx/cm_core.py\", line 215, in cm_complete_timeout\r\n    self._refresh_completions(ctx)\r\n  File \"/home/rafael/Dropbox/dotfiles/.vim/bundle/nvim-completion-manager/pythonx/cm_core.py\", line 481, in _refresh_completions\r\n    self._complete(ctx, startcol, matches)\r\n  File \"/home/rafael/Dropbox/dotfiles/.vim/bundle/nvim-completion-manager/pythonx/cm_core.py\", line 531, in _complete\r\n    self._nvim.call('cm#_core_complete', ctx, startcol, matches, not_changed)\r\n  File \"/usr/local/lib/python3.4/dist-packages/neovim/api/nvim.py\", line 230, in call\r\n    return self.request('nvim_call_function', name, args, **kwargs)\r\n  File \"/usr/local/lib/python3.4/dist-packages/neovim/api/nvim.py\", line 131, in request\r\n    res = self._session.request(name, *args, **kwargs)\r\n  File \"/usr/local/lib/python3.4/dist-packages/neovim/msgpack_rpc/session.py\", line 94, in request\r\n    raise IOError('EOF')\r\nOSError: EOF\r\n2017-03-03 11:15:14,513 [DEBUG @ base.py:run:138] 6073 - Entering event loop\r\n2017-03-03 11:15:14,513 [DEBUG @ msgpack_stream.py:_on_data:54] 6073 - waiting for message...\r\n2017-03-03 11:15:14,513 [DEBUG @ msgpack_stream.py:_on_data:56] 6073 - received message: [1, 21, None, 0]\r\n2017-03-03 11:15:14,513 [DEBUG @ async_session.py:_on_response:95] 6073 - received response: None, 0\r\n2017-03-03 11:15:14,513 [DEBUG @ base.py:stop:149] 6073 - Stopped event loop\r\n2017-03-03 11:15:14,513 [DEBUG @ msgpack_stream.py:_on_data:54] 6073 - waiting for message...\r\n2017-03-03 11:15:14,513 [DEBUG @ msgpack_stream.py:_on_data:59] 6073 - unpacker needs more data...\r\n2017-03-03 11:15:14,513 [DEBUG @ base.py:run:140] 6073 - Exited event loop\r\n2017-03-03 11:15:14,513 [INFO @ cm_start.py:run_event_loop:158] 6073 - received falsy value[None], exitting\r\n```\r\n\r\nThere's an `EOF` exception inside `session.py` when nvim-completion-manager process is trying to `    self._nvim.call('cm#_core_complete', ctx, startcol, matches, not_changed)`\r\n\r\nThe interesting part is the `received message: [1, 21, None, 0]` after the `EOF`, which seems to be the response of previous neovim function call. I'm not sure whether  I'm using this library the right way, but IMO  this implies that the `EOF` is not a correct message.\r\n",
    "closed_at": null,
    "closed_by": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/251/comments",
    "created_at": "2017-03-04T01:23:08Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/251/events",
    "html_url": "https://github.com/neovim/pynvim/issues/251",
    "id": 211843095,
    "issue_dependencies_summary": {
        "blocked_by": 0,
        "blocking": 0,
        "total_blocked_by": 0,
        "total_blocking": 0
    },
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/251/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUyMTE4NDMwOTU=",
    "number": 251,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/251/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "open",
    "state_reason": null,
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/251/timeline",
    "title": "`nvim.next_message`  returns None without EOF",
    "type": {
        "color": "red",
        "created_at": "2024-01-25T10:10:19Z",
        "description": "An unexpected problem or behavior",
        "id": 597163,
        "is_enabled": true,
        "name": "Bug",
        "node_id": "IT_kwDOAGK_Pc4ACRyr",
        "updated_at": "2024-07-26T10:12:30Z"
    },
    "updated_at": "2025-09-22T19:35:53Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/251",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/4538941?v=4",
        "events_url": "https://api.github.com/users/roxma/events{/privacy}",
        "followers_url": "https://api.github.com/users/roxma/followers",
        "following_url": "https://api.github.com/users/roxma/following{/other_user}",
        "gists_url": "https://api.github.com/users/roxma/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/roxma",
        "id": 4538941,
        "login": "roxma",
        "node_id": "MDQ6VXNlcjQ1Mzg5NDE=",
        "organizations_url": "https://api.github.com/users/roxma/orgs",
        "received_events_url": "https://api.github.com/users/roxma/received_events",
        "repos_url": "https://api.github.com/users/roxma/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/roxma/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/roxma/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/roxma",
        "user_view_type": "public"
    }
}